services:
  mysql:
    image: mysql:lts
    container_name: mysql
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:5.2.2-fpm-alpine
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
    volumes:
      - shared-pma:/var/www/html
    depends_on:
      - mysql
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - shared-pma:/var/www/phpmyadmin:ro
    depends_on:
      - phpmyadmin
    #restart: unless-stopped
volumes:
  shared-pma:
